[package]
name = "nusa-gateway"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Axum HTTP gateway with middleware chain"

[dependencies]
nusa-core = { path = "../nusa-core" }
nusa-plugin-api = { path = "../nusa-plugin-api" }
nusa-telemetry = { path = "../nusa-telemetry" }
nusa-octane-worker = { path = "../nusa-octane-worker" }
nusa-ipc = { path = "../nusa-ipc" }
nusa-config = { path = "../nusa-config" }
axum = { workspace = true, features = ["ws"] }
quinn = "0.11"
x509-parser = "0.17"
tower.workspace = true
tower-http.workspace = true
tokio.workspace = true
tracing.workspace = true
metrics.workspace = true
metrics-exporter-prometheus.workspace = true
serde_json.workspace = true
uuid.workspace = true
http.workspace = true
parking_lot.workspace = true
arc-swap.workspace = true
dashmap.workspace = true
moka.workspace = true
tokio-tungstenite.workspace = true
redis.workspace = true
futures.workspace = true
async-stream.workspace = true
rustls = { version = "0.23", features = ["ring"] }
rustls-pki-types.workspace = true
anyhow.workspace = true

rcgen = "0.13"

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
bytes.workspace = true
async-trait.workspace = true
urlencoding = "2"
