[package]
name = "nusa-engine-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "PHP WASM sandbox engine (wasmtime)"

[dependencies]
nusa-core = { path = "../nusa-core" }
wasmtime.workspace = true
wasmtime-wasi.workspace = true
tracing.workspace = true
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
http.workspace = true
wat.workspace = true
