//! Laravel-oriented path detection and config normalization.

use std::path::{Path, PathBuf};

use crate::RuntimeConfig;

/// Laravel paths that need RW under Landlock (file session/cache/logs).
pub fn writable_dirs(code_dir: &Path) -> Vec<PathBuf> {
    let base = PathBuf::from(code_dir);
    [base.join("storage"), base.join("bootstrap").join("cache")]
        .into_iter()
        .collect()
}

/// Standard container layout (`WORKDIR /app`).
pub fn container_defaults() -> RuntimeConfig {
    let mut cfg = crate::builtin_defaults();
    cfg.code_dir = "/app".into();
    cfg.vfs_root = String::new();
    cfg.tmp_dir = "/tmp/nusa".into();
    cfg.bind = "0.0.0.0:8080".into();
    cfg.hot_reload = false;
    cfg
}

/// Fix common misconfigurations (e.g. `code_dir` pointing at `public/` only).
pub fn normalize_paths(cfg: &mut RuntimeConfig) {
    let code = PathBuf::from(&cfg.code_dir);

    if code.join("artisan").is_file() {
        if cfg.vfs_root.is_empty() {
            cfg.vfs_root = code.join("public").to_string_lossy().into();
        }
        return;
    }

    if code.join("index.php").is_file()
        && let Some(parent) = code.parent()
        && parent.join("artisan").is_file()
    {
        cfg.vfs_root = cfg.code_dir.clone();
        cfg.code_dir = parent.to_string_lossy().into();
    }
}

/// Detect Laravel project root from `start_dir` (walks up to 6 parents).
pub fn detect_project_root(start_dir: &Path) -> Option<PathBuf> {
    let mut dir = start_dir.to_path_buf();
    for _ in 0..7 {
        if dir.join("artisan").is_file() {
            return Some(dir);
        }
        if !dir.pop() {
            break;
        }
    }
    None
}

/// Render a starter `nusa.toml` for the given project root.
pub fn render_starter_toml(root: &Path, octane_workers: usize) -> String {
    let root_s = root.to_string_lossy();
    let tmp = std::env::temp_dir()
        .join("nusa")
        .to_string_lossy()
        .into_owned();
    format!(
        r#"# Generated by `nusa init` — Laravel plug-and-play starter
engine = "child"
octane_workers = {octane_workers}
code_dir = "{root_s}"
vfs_root = "{root_s}/public"
tmp_dir = "{tmp}"
max_workers = 4
timeout_ms = 30000
hot_reload = true
bind = "127.0.0.1:8080"
php_binary = "php"
"#
    )
}
